<?php

namespace App\Exports;

use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use Maatwebsite\Excel\Concerns\FromCollection;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use App\Models\Setting;

class TransactionsExport implements FromCollection, WithStyles, WithDrawings, WithColumnWidths
{
    protected $transactions;
    protected $siteName;
    protected $startDate;
    protected $endDate;
    protected $user;
    protected $aiAudit;
    protected $logoPath;

    const GREEN = '7A9A7E';
    const GREEN_DARK = '5F7D63';
    const BORDER = 'D9E2D9';
    const TEXT = '1F2937';
    const MUTED = '4B5563';

    public function __construct($transactions, $siteName, $startDate, $endDate, $user, $aiAudit = null, $logoPath = null)
    {
        $this->transactions = $transactions;
        $this->siteName = $siteName;
        $this->startDate = date('d M, Y', strtotime($startDate));
        $this->endDate = date('d M, Y', strtotime($endDate));
        $this->user = $user;
        $this->aiAudit = $aiAudit ?? "No dynamic insights compiled for this period timeline.";
        $this->logoPath = $logoPath ?? public_path('images/logo.png');
    }

    public function columnWidths(): array
    {
        return [
            'A' => 20,
            'B' => 32,
            'C' => 20,
            'D' => 18,
            'E' => 20,
        ];
    }

    public function drawings()
    {
        $settings = Setting::first();

        $drawing = new Drawing();
        $drawing->setName('Logo');
        $drawing->setDescription('Site Logo');

        $drawing->setPath(
            public_path(
                str_replace(url('/'), '', $settings->site_logo)
            )
        );

        $drawing->setOffsetX(4);
        $drawing->setOffsetY(2);
        $drawing->setHeight(50);
        $drawing->setCoordinates('E3');
        return [$drawing];
    }

    public function collection()
    {
        $rows = collect();

        // Row 1: Thin title bar
        $rows->push(['BALANCE SHEET REPORT']);
        $rows->push(['']); // spacing

        // Row 3-6: Company block (left) — logo image floats over column E here
        $rows->push([strtoupper($this->siteName)]);
        $rows->push(['Reliable Financial Ecosystem Intelligence']);
        $rows->push([$this->user->email]);
        $rows->push(['As of: ' . date('d M, Y h:i A')]);
        $rows->push(['']); // spacing

        // Row 8: Prepared By / Statement Period
        $rows->push(['PREPARED BY', $this->user->name, '', 'STATEMENT PERIOD', $this->startDate . ' - ' . $this->endDate]);

        $totalIncome = $this->transactions->filter(fn($t) => ($t->category?->type ?? $t->type) === 'income')->sum('amount');
        $totalExpense = $this->transactions->filter(fn($t) => ($t->category?->type ?? $t->type) === 'expense')->sum('amount');
        $netBalance = $totalIncome - $totalExpense;
        $savingsRate = $totalIncome > 0 ? round(($netBalance / $totalIncome) * 100, 1) : 0;

        // Row 9: Total Income / Total Expense
        $rows->push(['TOTAL INCOME', 'Rs. ' . number_format($totalIncome, 2), '', 'TOTAL EXPENSE', 'Rs. ' . number_format($totalExpense, 2)]);

        // Row 10: Net Balance / Savings Rate
        $rows->push(['NET BALANCE', 'Rs. ' . number_format($netBalance, 2), '', 'SAVINGS RATE', $savingsRate . '%']);

        // Row 11: AI Audit Notes (label + merged value)
        $rows->push(['AI AUDIT NOTES', $this->aiAudit]);
        $rows->push(['']); // spacing

        // Row 13: Table headers
        $rows->push(['DATE', 'DESCRIPTION', 'CATEGORY', 'AMOUNT', 'RUNNING (PKR)']);

        foreach ($this->transactions as $tx) {
            $txType = $tx->category?->type ?? $tx->type ?? 'expense';
            $currencySymbol = match ($tx->currency) {
                'USD' => '$ ', 'EUR' => '€ ', 'AED' => 'د.إ ', 'GBP' => '£ ', default => 'Rs. ',
            };
            $localAmount = $tx->actual_amount ?? $tx->amount;
            $sign = ($txType === 'income') ? '+' : '-';

            $rows->push([
                date('d M, Y', strtotime($tx->date)),
                $tx->description ?? 'General Item Allocation',
                $tx->category?->name ?? 'Uncategorized',
                $sign . $currencySymbol . number_format($localAmount, 2),
                'Rs. ' . number_format($tx->amount, 2),
            ]);
        }

        $rows->push(['']); // spacing
        $rows->push(['Signed by:', '', '', '* Auto-generated by ' . strtoupper($this->siteName)]);

        return $rows;
    }

    public function styles(Worksheet $sheet)
    {
        // 1. Title bar (Row 1)
        $sheet->mergeCells('A1:E1');
        $sheet->getRowDimension(1)->setRowHeight(24);
        $sheet->getStyle('A1')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::GREEN);
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(13)->setColor(new Color('FFFFFF'));
        $sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER)->setVertical(Alignment::VERTICAL_CENTER);
        $sheet->getStyle('A1:E1')->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB(self::GREEN_DARK);

        // 2. Company block (Rows 3-6) — logo floats beside this in column E via drawings()
        $sheet->getStyle('A3')->getFont()->setBold(true)->setSize(12)->setColor(new Color(self::TEXT));
        $sheet->getStyle('A4')->getFont()->setSize(9)->setColor(new Color(self::MUTED));
        $sheet->getStyle('A5')->getFont()->setSize(9)->setColor(new Color(self::MUTED));
        $sheet->getStyle('A6')->getFont()->setSize(9)->setColor(new Color(self::MUTED));
        $sheet->getRowDimension(3)->setRowHeight(16);

        // 3. Prepared By / Statement Period (Row 8)
        $sheet->getStyle('A8')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::GREEN);
        $sheet->getStyle('A8')->getFont()->setBold(true)->setColor(new Color('FFFFFF'))->setSize(10);
        $sheet->getStyle('D8')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::GREEN);
        $sheet->getStyle('D8')->getFont()->setBold(true)->setColor(new Color('FFFFFF'))->setSize(10);
        $sheet->getStyle('B8')->getFont()->setSize(10)->setColor(new Color(self::TEXT));
        $sheet->getStyle('E8')->getFont()->setSize(10)->setColor(new Color(self::TEXT));
        $sheet->getStyle('A8:B8')->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB(self::BORDER);
        $sheet->getStyle('D8:E8')->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB(self::BORDER);

        // 4. Total Income / Total Expense (Row 9)
        foreach (['A9', 'D9'] as $cell) {
            $sheet->getStyle($cell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::GREEN);
            $sheet->getStyle($cell)->getFont()->setBold(true)->setColor(new Color('FFFFFF'))->setSize(10);
        }
        $sheet->getStyle('B9')->getFont()->setBold(true)->setSize(10)->setColor(new Color(self::TEXT));
        $sheet->getStyle('E9')->getFont()->setBold(true)->setSize(10)->setColor(new Color(self::TEXT));
        $sheet->getStyle('A9:B9')->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB(self::BORDER);
        $sheet->getStyle('D9:E9')->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB(self::BORDER);

        // 5. Net Balance / Savings Rate (Row 10)
        foreach (['A10', 'D10'] as $cell) {
            $sheet->getStyle($cell)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::GREEN);
            $sheet->getStyle($cell)->getFont()->setBold(true)->setColor(new Color('FFFFFF'))->setSize(10);
        }
        $sheet->getStyle('B10')->getFont()->setBold(true)->setSize(10)->setColor(new Color(self::TEXT));
        $sheet->getStyle('E10')->getFont()->setBold(true)->setSize(10)->setColor(new Color(self::TEXT));
        $sheet->getStyle('A10:B10')->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB(self::BORDER);
        $sheet->getStyle('D10:E10')->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB(self::BORDER);

        // 6. AI Audit Notes (Row 11)
        $sheet->mergeCells('B11:E11');
        $sheet->getStyle('A11')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::GREEN);
        $sheet->getStyle('A11')->getFont()->setBold(true)->setColor(new Color('FFFFFF'))->setSize(10);
        $sheet->getStyle('A11')->getAlignment()->setVertical(Alignment::VERTICAL_TOP);
        $sheet->getStyle('B11')->getFont()->setItalic(true)->setSize(9)->setColor(new Color(self::MUTED));
        $sheet->getStyle('A11:E11')->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB(self::BORDER);
        $sheet->getRowDimension(11)->setRowHeight(32);
        $sheet->getStyle('B11')->getAlignment()->setWrapText(true)->setVertical(Alignment::VERTICAL_TOP);

        // 7. Table header (Row 13)
        $thStyle = [
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 10],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => self::GREEN]],
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => self::GREEN_DARK]]],
        ];
        $sheet->getStyle('A13:E13')->applyFromArray($thStyle);
        $sheet->getStyle('D13:E13')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);

        // 8. Data rows — plain white, thin borders, right-aligned amounts
        $highestRow = $sheet->getHighestRow();
        for ($row = 14; $row < $highestRow; $row++) {
            $sheet->getStyle("A{$row}:E{$row}")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB(self::BORDER);
            $sheet->getStyle("D{$row}:E{$row}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        }

        // 9. Footer (last row)
        $sheet->getStyle("A{$highestRow}")->getFont()->setSize(10)->setColor(new Color(self::TEXT));
        $sheet->mergeCells("D{$highestRow}:E{$highestRow}");
        $sheet->getStyle("D{$highestRow}")->getFont()->setItalic(true)->setSize(9)->setColor(new Color(self::MUTED));
        $sheet->getStyle("D{$highestRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);

        $sheet->getParent()->getDefaultStyle()->getFont()->setName('Calibri')->setSize(10);

        return [];
    }
}
